### ISSUE TITLE
Option to have schedule entity entry information with ending time and identifier for action similar to version 2.1.1 entity

### ISSUE THREAD

**Issue by GoofiaX** [nielsfaber/scheduler-component#118]
Please consider option / extra line for schedule -entities state that shows the timeslots with the style similar to 2.1.1

Example from 2.1.1 entity in HA:

entries: 0DT0300T0800A0, 0DT1400T2000A1
actions: 
- service: set_value
  entity: input_number.[redacted]_heattime
  value: 0
- service: set_value
  entity: input_number.[redacted]_heattime
  value: 1

next_trigger: 2021-08-26T14:00:00+03:00
friendly_name: [redacted]
icon: mdi:calendar-clock

So crucial need is the ending time of a timeslot and the action (A0, A1...) identifier.

This would make a lot easier to implement different automations (= node-red functions) on the basis of this schedule component.

**Comment by nielsfaber** [comment]
> Please consider option / extra line for schedule -entities state that shows the timeslots with the style similar to 2.1.1

The need for such formatting was dropped since the migration to websockets.
There is no reason to add it again.

The current exposed attributes are more 'human readable' like such:

![image](https://user-images.githubusercontent.com/16861605/134229956-c0ec7a81-e962-4ba3-ab74-b42ce807564b.png)

Corresponding schedule configuration is as such:
![image](https://user-images.githubusercontent.com/16861605/134230135-beadcdfe-b40e-4be5-94a5-5e5ae7308634.png)

What seems to be missing is:
- indication of end times for slots
- mapping from timeslots to actions

How would you propose to have this exposed in the entity attributes?
