### ISSUE TITLE
Retry thermostat setpoint change

### ISSUE THREAD

**Issue by 2m** [nielsfaber/scheduler-component#151]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting. (somewhat similar previous ticket #76)
- [x] My request is generic, other users may benefit from it too.

### Proposal

I am running zigbee2mqtt with Drayton Wiser iTRV. Unfortunately these iTRVs sometimes miss setpoint change. When changing it manually, usually it is instant, but sometimes I need to repeat the change two or three times, until it sticks https://github.com/Koenkk/zigbee2mqtt/issues/2521#issuecomment-974387056.

Naturally this causes setpoint change by the scheduler-component sometimes to be missed.

Would it make sense to implement retry logic in the scheduler-component?

**Comment by nielsfaber** [comment]
I am not planning on implementing such logic within scheduler-component.
My intention is to keep it generic, so it does not have different behaviour for climate, light etc.
I guess the real solution for your problem has to be made in zigbee2mqtt, as the problem is caused in the communication with the device.
As workaround you could implement some script which watches for scheduler to trigger and repeats its task (indeed you could make use the `scheduler.run_action` service for this.
Its also possible to trigger a script from scheduler, and implement your custom sequence here.
I'm afraid that's all I can offer as solution.

**Comment by 2m** [comment]
Hey, thanks for the answer. I think it is fair enough. :) Will try to see if I can help to solve the actual problem in Z2M, or will think about a workaround.
