### ISSUE TITLE
Arrange schedules & Copy schedule

### ISSUE THREAD

**Issue by djremco** [nielsfaber/scheduler-component#158]
Hi Niels,

First off all great work making this plugin for HA we where defiantly missing something like this (goed bezig).
I do have two feature request:

- Cloud / Would you be able to make it possible to arrange the schedules with like a drag & drop so we would be able to put the schedules for winter together and summer together etc.

- Could / Would you be able to make it possible to copy an schedule so you don have to start form scratch when making schedules with a lot of the same settings and conditions. 

Keep up the good work,

Regards,

Remco
HA Addict

**Comment by haseat** [comment]
> * Could / Would you be able to make it possible to copy an schedule so you don have to start form scratch when making schedules with a lot of the same settings and conditions.

You can copy schedules in Developer Tools > Services

![image](https://user-images.githubusercontent.com/61622258/146136741-935f9e87-9a32-4af3-8dbf-c74b7ed27495.png)

**Comment by nielsfaber** [comment]
Hi @djremco  🙂 

> Cloud / Would you be able to make it possible to arrange the schedules with like a drag & drop so we would be able to put the schedules for winter together and summer together etc.

The preferred way to divide schedules is to assign them with different tags.
If you have multiple scheduler-cards, you can give each one a different tag such that your winter / summer schedules always remain separated.

I don't think a drag & drop feature is realistic, since the list is composed _dynamically_. In other words, the scheduler-card checks which schedules you have in your system, and filters them based on the card configuration. 
This is completely different compared to for example the [entities card](https://www.home-assistant.io/lovelace/entities/), since here the user needs to define a fixed list of entity_id's to be included in the card, which is stored in the card configuration.
The scheduler-card doesn't keep such a list, hence it can also not keep them in a predefined order.
The only possibility I see is to define more sorting rules (as requested [here](https://github.com/nielsfaber/scheduler-card/issues/472)).

> Could / Would you be able to make it possible to copy an schedule so you don have to start form scratch when making schedules with a lot of the same settings and conditions.

As @haseat says, copying a schedule is already possible via the scheduler.copy service. There is no button for this in the card, adding things in the card is always a bit of a puzzle since I see it too full already. I guess the copy service is sufficient, since I think 9/10 users would start with an empty schedule.
