### ISSUE TITLE
Custom light/dark times 

### ISSUE THREAD

**Issue by apocaliss92** [nielsfaber/scheduler-component#160]
Would be cool to be able to provide a configuration for a sensor containing custom times for light and dark times to trigger the scheduler instead of the sun integration

### Additional info
My use case is a light sensor I have installed outside my home and setting the desired lumens when it's dark enough. Therefor I can save the light/dark time for the next day to use within the scheduler

**Comment by KTibow** [comment]
Why though? Is the sun integration inaccurate for you or something?

**Comment by nielsfaber** [comment]
I have no intention to support schedules to trigger based on anything other than time or sun.
If you really want this, you can create some sensor entity and use it as replacement of the sun entity. For this you need to modify this line and place your sensor entity instead:
https://github.com/nielsfaber/scheduler-component/blob/89efd47254306d4eba4e6f58a62978906c2c19b6/custom_components/scheduler/const.py#L22

Note that scheduler checks the `next_rising` and `next_setting` attributes, so you will have to add these to your sensor.
Otherwise I cannot help you.
