### ISSUE TITLE
Add condition for single action in time scheme from card.

### ISSUE THREAD

**Issue by Pigi-102** [nielsfaber/scheduler-component#177]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
[clear description of what you want to see changed or added]
It would be nice to be able to set a condition only for a time slot when using scheme to gain more granularity over configurations.
It seems to be possible to do this from the "scheduler.storage" file but not get reflected in UI
### Additional info
[some example of how the new functionality should look like]

My need ( but I don't think it's only mine ) is to, for example, turn on heat at specific time in the morning, but only if the temperature from a sensor is lower than a value:
Turn on heat at 6.30 AM in room temperature is below 18°  otherwise don't do nothing.

**Comment by calisro** [comment]
I have this same requirement.  If I set a condition for the schedule, it impacts both on and off.  Really what I need is to say don't turn on unless its true.  The only way to achieve this currently is to setup multiple different on and off schedules.

**Comment by nielsfaber** [comment]
This request belongs in scheduler-card, not in scheduler-component.
The scheduler-component can already handle conditions per timeslot, the card cannot.
I am not planning to add this to the card, since I think it would make the UI very complex.
As a workaround you could play with the conditions. E.g.:
> If room temperature is below 18 OR thermostat is not off

Would effectively cause the timeslots where thermostat should be turned off to always be executed, so the 'temperature below 18' part applies to the timeslots where the thermostat should start heating.
