### ISSUE TITLE
Make Sunrise / Sunset Offset bigger

### ISSUE THREAD

**Issue by MaxRei-dev** [nielsfaber/scheduler-component#183]
Hi,
now ist only supports +-2:00h. maybe this could be changed to eg. +-5:00h ?
Thank you

**Comment by nielsfaber** [comment]
This has been discussed before, but I'm choosing not to do that.
The main reason is that schedules could become corrupted when the times exceed the span of a day (00:00 - 23:59) due to sun shift. For example in my country 5 hours after sunset could be around 22:00 in the winter, but 03:00 in the summer (which is the next day, and scheduler cannot process that).
Another reason is that 5 hours after sunrise, the sun is completely up. So the configured time has nothing to do with the sun.
Often I hear people are just looking for a way to add some 'randomness' to the configured times, but this is not the right way.
I hope you can accept the limitations.

**Comment by MaxRei-dev** [comment]
Hi,
Thanks for the explanation. 
Maybe you can tell me where to set it in the source files. 
I would need it for setting the Hot Water temperature when the sun is up for 3h in the wintertime because otherwise the sun is not fully on my PV pannels. i hope you know what i mean. so sunrise would be enough for me. 
On the other hand maybe there is a way to set an time-helper as start / end time.. ?
