### ISSUE TITLE
Scheduler can’t open 9 somfy covers.

### ISSUE THREAD

**Issue by lecynophile** [nielsfaber/scheduler-component#189]
Hi, 
I’m sorry for my english. I Hope you understand. 

I think i found a bug. I scheduled to close all the covers 30’ after the sunrise . I’ve 9 covers but every days only 7 are closing after the request. Maybe there are too much commands in the same time for the SOMFY hub. 
Do you think it’s possible to delayed the request of the covers one by one ? 

Thank’s for reading me. 😄

**Comment by nielsfaber** [comment]
I think this limitation is caused by the Somfy integration (or hub) rather than scheduler.
If you want to delay the commands between covers, you could either divide them over multiple schedules (1 minute apart) or define a sequence with delays in a script and use scheduler to trigger that instead.
There is no option to add configurable delay between tasks currently.
Did you try putting all covers in a group and perform a close/open action on this group instead? Perhaps it works more reliable in HA.

**Comment by lecynophile** [comment]
I think you are right. 

I didn’t try putting all covers in a group, because I was the first time in HA. So I used a script and a button and it works really well. It’s sequential process 
For tonight I’m trying to ask scheduler closing 30’ after sunrising two groups of covers. 
Thank you, I’ll keep you informed
