### ISSUE TITLE
Suggestion: Add multiple devices / schedules

### ISSUE THREAD

**Issue by feradelectronics** [nielsfaber/scheduler-component#20]
Really nice scheduler.  Hope it evolves quickly and becomes part of the core home assistant features.

Please add the ability to have multiple schedules.  Maybe add / separate new devices for each schedule.  The ability to have different schedules on different lovelace pages.

eg. 
 - outdoor page can have schedule for outdoor lighting
 - basement page can have schedule for different automations
 - alarm page can have schedule for auto arming at specific times

**Comment by nielsfaber** [comment]
Thanks for your enthousiasm, I hope it will stay that way 🙂 
First of all, i think your issue is related to the [scheduler-card](https://github.com/nielsfaber/scheduler-card).
The component only takes care of storing the schedules and executing the actions, the visualization and managing of schedules is done in the card.

I am not sure if I completely understand your request.
There is already the possibility to create multiple instances of `scheduler-card`.
You should [configure](https://github.com/nielsfaber/scheduler-card#general) each of the cards to show up only the entities you want.
Summary of the steps:
- [ ] Set `standard_configuration:false` to not list all lights, switches, covers, climates etc. in each card
- [ ] Define your the `domains` or `entities` configuration for each card to tell the card which (type of) entities you want to show up
- [ ] Set `discover_existing:false` to not cause all your created schedules to show up in each card, even if they are not included in your configuration 

Hope this covers your question.

**Comment by KTibow** [comment]
@feradelectronics was asking two different questions:
1.  > Maybe add / separate new devices for each schedule.
2.  > The ability to have different schedules on different lovelace pages.

**Comment by nielsfaber** [comment]
Please explain
_Maybe add / separate new devices for each schedule._ 

In HA context, a device refers to a [collection of entities](https://developers.home-assistant.io/docs/device_registry_index/), don't think this is what we are looking for.

**Comment by KTibow** [comment]
Probably @feradelectronics means entities. It would be interesting to add device actions though...

**Comment by feradelectronics** [comment]
> Really nice scheduler. Hope it evolves quickly and becomes part of the core home assistant features.
> 
> Please add the ability to have multiple schedules. Maybe add / separate new devices for each schedule. The ability to have different schedules on different lovelace pages.
> 
> eg.
> 
> * outdoor page can have schedule for outdoor lighting
> * basement page can have schedule for different automations
> * alarm page can have schedule for auto arming at specific times

**Comment by nielsfaber** [comment]
@feradelectronics  say what?

**Comment by feradelectronics** [comment]
allow multiple devices with schedules for different entitites.  Different lovelace pages could include the schedules appropriate for that page

**Comment by nielsfaber** [comment]
There is already support for multiple scheduler-cards, you can configure it yourself.
