### ISSUE TITLE
2 hours before and after sunset

### ISSUE THREAD

**Issue by Tanjohnson99** [nielsfaber/scheduler-component#212]
Hello, 

Increase more than 2 hour before and after sunset.

Thanks

**Comment by Tanjohnson99** [comment]
No solution to select more tha 2 hours before and after sunset ? 

Best

**Comment by nielsfaber** [comment]
This has been requested before but it will not be added.
The main reason is that a schedule could easily become corrupted (e.g. sunrise - 5 hours could be the previous day, or begin and end time for a timeslot may become reversed).
Additionally, scheduling a task with more than 2 hours offset is not meaningful, since the sun will be already completely up or down.
