### ISSUE TITLE
Nashone mts700 tuya thermostat not 100%

### ISSUE THREAD

**Issue by GroenZoom** [nielsfaber/scheduler-component#216]
### Checklist
- x] I checked for similar existing issues (both open and closed) before posting.
- x ] I am running the latest version.

### Expected behavior
When scheduler switches Nashone off it should go to off and not displayed in history graph as color filled anymore.

### Actual behavior
When scheduler switches the Nashone off as programmed it stays on Heating (Off) and in HA history with color filled graph.

### Steps to Reproduce
Program scheduler for heating with Nashone mts700  in sequence off>heating>off , thermostat is still shown as activated. 
![Image1](https://user-images.githubusercontent.com/50486182/195808379-a4fd7740-d12e-4fd7-a6c9-15e12b7b35d6.jpg)

**Comment by nielsfaber** [comment]
When you select action ‘turn off’ in the scheduler, it will execute the service climate.turn_off OR the service climate.set_hvac_mode with hvac_mode = off in case your device supports it.
If the device doesn’t respond to the command correctly, this is not due to scheduler. I think the problem is on the device side.
You can test the response of the device to such service yourself, by going to Developer Tools -> Services. This should give the same effect.

**Comment by GroenZoom** [comment]
Thanks for your prompt response and suggestion.

mvrgr
Martin

Van: Niels Faber
Verzonden: vrijdag 14 oktober 2022 20:57
Aan: nielsfaber/scheduler-component
CC: GroenZoom; Author
Onderwerp: Re: [nielsfaber/scheduler-component] Nashone mts700 tuya thermostatnot 100% (Issue #216)

When you select action ‘turn off’ in the scheduler, it will execute the service climate.turn_off OR the service climate.set_hvac_mode with hvac_mode = off in case your device supports it.
If the device doesn’t respond to the command correctly, this is not due to scheduler. I think the problem is on the device side.
You can test the response of the device to such service yourself, by going to Developer Tools -> Services. This should give the same effect.
