### ISSUE TITLE
Feature request: Recurring schedules

### ISSUE THREAD

**Issue by frozendevl** [nielsfaber/scheduler-component#22]
Hi Niel,

Great job on the scheduler so far! I would like to request a feature that allows to set recurring schedules within the same schedule job.

Use case: I have a fan that I want to turn on every every 2 hours and turn it off every 2 hours (alternating between the two, so that it's on for an hour and off for an hour). This would require me to set and manage 24 different schedules.

**Comment by nielsfaber** [comment]
I agree that a _scheduler_ should be able to run things periodically.
I must say that adding it is not very straight-forward though, since many parts are really working based on a time+day combination.

Somewhere next week i plan to release an update, allowing you to group multiple actions within the same schedule.
I think this should help already.

Dealing with your feature request will take a bit longer though, this is not really a priority right now.
Thanks for the idea, i will think about it.

**Comment by frozendevl** [comment]
Appreciate the response. I'm okay with this being a low priority/not a
priority, since I'm not sure how useful this is to people using the
scheduler. I was able to solve my use case with a cron job in node-red.

**Comment by nielsfaber** [comment]
Did you try the time scheme editor?
It allows you to plan multiple tasks for different timeslots.
It should do more-or-less what you want.

Time to clean up old issues.. Please re-open if the issue is not resolved.
