### ISSUE TITLE
Scheduler Component will not integrate

### ISSUE THREAD

**Issue by Hypergossi** [nielsfaber/scheduler-component#250]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
Scheduler should add as in integration when selected.

### Actual behavior
I've followed the instructions and installed via HACS. When I go to add the integration Scheduler shows in the list, however when I click on Scheduler it does not install and is not added to the integrations list. I've tried uninstalling and reinstalling multiple times, I've cleared my cache multiple times, and tried across multiple browsers as well as the home assistant app, the result is always the same.

I've also checked the scheduler folder in file editor and all installed files seem to be there.

### Steps to Reproduce
As per my behaviour.

**Comment by nielsfaber** [comment]
If the scheduler component is properly installed you should see this message in the HA log on startup:
> We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

If this message shows up, you should go to the Configuration -> Devices page and add scheduler as integration.
If the item is not in the list, the problem is for sure related to browser cache and you can only fix this yourself.
