### ISSUE TITLE
Scheduler card does not appear in the list of cards after installation

### ISSUE THREAD

**Issue by 11110110011** [nielsfaber/scheduler-component#283]
After updating Home Assistant core to version  2023.7.3, scheduler card has suddenly dropped from HA.   Reinstallation of both scheduler component and integration does not help, scheduler card does still not appears in the list of lovelace cards.

<img width="331" alt="image" src="https://github.com/nielsfaber/scheduler-component/assets/32438754/082f7930-d412-4979-9722-6b679c28f626">

<img width="761" alt="image" src="https://github.com/nielsfaber/scheduler-component/assets/32438754/8c534999-b9eb-460d-b2ae-da6f57e3c9e5">

HACS installation:
<img width="853" alt="image" src="https://github.com/nielsfaber/scheduler-component/assets/32438754/c1380f30-e8ee-432f-8e78-022138c817b1">

<img width="212" alt="image" src="https://github.com/nielsfaber/scheduler-component/assets/32438754/a530d9c3-6d55-4990-b7c2-070349f048bf">

Integration:
<img width="752" alt="image" src="https://github.com/nielsfaber/scheduler-component/assets/32438754/37e2b917-364f-4907-8272-43438243429e">

There are no issues related to scheduler card in the log file.

**Comment by nielsfaber** [comment]
The card for scheduler needs to be installed separately via HACS. Please check if it is installed.

**Comment by 11110110011** [comment]
It was not, now it is installed but the card is not on the list. System restart does not help.

<img width="862" alt="image" src="https://github.com/nielsfaber/scheduler-component/assets/32438754/5dfb3807-4910-4ca6-95d9-f199a5118e82">

**Comment by 11110110011** [comment]
I cleared the browser cash, everything works now. Thank you!

**Comment by 11110110011** [comment]
> Hi,
> I have got the same problem.
> 
> Scheduler and Scheduler cards installed via HACS.
> Home Assistant 2023.7.3
> cleared browser cache
> 
> Tried it with Safari, Firefox, Chrome and Edge.
> 
> I click on 'add item', a window appeared but the window is empty. "Scheduler, a '?' a 'X' and 'close'.
> 
> Du you have an idea?
> 
> Best regards
> hoeffy

Check if Scheduler integration (not in HACS) is installed in addition to these two. Seems like all three components are required.  This way it works in my HA.

**Comment by mishehou** [comment]
I was running the component for several years now without problems. since last week  (Ver 2023.7.3?) the cards are not displayed anymore. 

It seems there are somewhere in the background , but not appearing anywhere. where the cards used to be, there is a message now reading: "Could not connect with the scheduler component. It needs to be installed as integration before this card can be used." 
However, the card and the integration are both installed and active!

Emptying the cache didn't solve anything


![Screenshot 2023-07-30 at 16 03 41](https://github.com/nielsfaber/scheduler-component/assets/46596030/df47af9c-ff2f-4757-9dc9-f4bb9a139f81)
