### ISSUE TITLE
Schedules are turned off or not triggering

### ISSUE THREAD

**Issue by Marvin3241** [nielsfaber/scheduler-component#352]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.13

### Bug description

My schedules are often turned off after triggering. For example, I have a schedule that should trigger 3 or 4 times during the day but after the first trigger it turns itself off. Sometimes the schedule is not turned off, but it will say show that it is finished for the day and it will be waiting for the next schedule to trigger.
Here you can see the lowest schedule is turned off. This happened after it triggered.
![WhatsApp Image 2024-04-16 at 19 29 22](https://github.com/nielsfaber/scheduler-card/assets/65965837/98c067b7-3362-4672-b8a9-c73ec96e21b7)
Here you can see that there are still triggers planned for the day, but these won't be happening.
![WhatsApp Image 2024-04-16 at 19 29 23](https://github.com/nielsfaber/scheduler-card/assets/65965837/671fd336-4763-4256-87de-89faf506cb62)

### Steps to reproduce

To reproduce I created an input_number in the home assistant helpers and created a schedule with this number. I added multiple days to the schedule and set multiple triggers for each day. After the first trigger, the problem already occured.

**Comment by nielsfaber** [comment]
I haven't seen any issues with a schedule not triggering or disabling itself myself.
In my setup I use multiple schedules that trigger on a daily basis, so any broken functionality would be noticed.
There are no significant changes made to this component in over a year, so I have no idea what causes this recent issue (this is likely introduced by changes in HA).

If anyone has some reproduction scenario or error logs that could help identifying the issue, please share.
For those who want to contribute: it may be useful to install the [profiler](https://www.home-assistant.io/integrations/profiler/) integration and call service `profiler.set_asyncio_debug` (with enabled=true) to increase the likelihood of the problem occuring and catching the issue in the HA error logs.

**Comment by Farmer-Eds-Shed** [comment]
> @Farmer-Eds-Shed no need to be so defensive. I never said is was your fault. Just mentioning that with using automations to keep the Scheduler card/repository working the Scheduler does loose a lot of its added value. That has nothing to do with your workaround.

?? 
You asked a question on what benefit, and I simply answered. Obviously it was just a temporary workaround, regardless of loosing value or not I still need my hot water schedule to work even if it's in a baling twine and pallets sort of way. Others here may be in a similar predicament easy to remove the addition when all is fixed.

I didn't think you were assigning blame at all.

**Comment by Farmer-Eds-Shed** [comment]
> If anyone has some reproduction scenario or error logs that could help identifying the issue, please share.
> For those who want to contribute: it may be useful to install the [profiler](https://www.home-assistant.io/integrations/profiler/) integration and call service `profiler.set_asyncio_debug` (with enabled=true) to increase the likelihood of the problem occuring and catching the issue in the HA error logs.

I'm running that now on my instance

**Comment by Farmer-Eds-Shed** [comment]
Maybe this is useful?

```
Logger: homeassistant.util.logging
Source: util/logging.py:103
First occurred: 4:30:00 PM (1 occurrences)
Last logged: 4:30:00 PM

Exception in async_timer_finished when dispatching 'scheduler_timer_finished': ('396d91',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 258, in async_timer_finished await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 258, in async_queue_actions for queue in self._queues.values(): RuntimeError: dictionary changed size during iteration
```

**Comment by AppleFlapp** [comment]
Let me guess what happens next:
Tomorrow it shows "yesterday" instead of 4 minutes ago or any other expected update on the status and even if it is then 4:35 nothing has happened.

That is about what happens here for the daily open/close schedules of my covers.

Only a toggle of the schedule will bring the configured schedule back alive.

**Comment by nielsfaber** [comment]
@Farmer-Eds-Shed 
> Maybe this is useful? Schedule triggered at 4:30 but next trigger time is showing as 4 min ago

Are you sure you are running the latest version? I thought this error was adressed a while ago, see: https://github.com/nielsfaber/scheduler-component/issues/343

**Comment by deveon95** [comment]
I'm here because I have the same problem...

* I migrated my Home Assistant installation from a Raspberry Pi 3 to a Raspberry Pi 5 4GB a couple of weeks ago. My initial assumption was that this migration caused the fault and it might therefore be a good idea if everyone affected states what hardware they're using just in case it isn't a software fault.
* The migration method used was making a full backup then restoring this backup in the setup wizard on a fresh SD card. I haven't wiped the old SD card so I can put it back in the Pi 3 later and check what versions of relevant software it had installed.
* "Tomorrow it shows "yesterday" instead of 4 minutes ago or any other expected update on the status and even if it is then 4:35 nothing has happened" - this is exactly what happens to my installation too.
* I have schedules of various different types (make a scheme, run a script, turn on/off) and they are all affected. In the case of the 'make a scheme' ones, it will always stop at midnight, whereas the run a script will work on the next trigger time but not again after,

My software versions on the Pi 5 are:
* Scheduler 3.3.0
* Core 2024.4.4
* Supervisor 2024.04.4
* Operating System 12.2
* Frontend 20240404.2

I will check what the versions are on the Pi 3 SD card and report back.

**Comment by deveon95** [comment]
I forgot to mention that in my case, if a schedule is turned _off_, then the displayed time that it would run next if it were turned on is updated correctly.

The Pi 3 SD card has:

* Scheduler 3.3.0
* Core 2024.3.0
* Supervisor 2024.04.0
* Operating System 12.1
* Frontend 20240306.0

I disabled automatic updates so that I could manually update each component and see which one breaks it.

With the above versions, I set a schedule to run a script in a few minutes with daily repeat enabled, and the time updated as expected.

I then updated Home Assistant Supervisor to 2024.04.4, repeated the experiment, and again the time updated as expected.

Next, I updated the Home Assistant Operating System to 12.2, repeated the experiment, and again the time updated as expected.

After that, I updated Home Assistant Core to 2024.5.0, which had just come out, and the time has not updated (it shows as 3 minutes ago, etc.) and probably won't repeat tomorrow, so the fault is caused by a change to Home Assistant Core and the version which introduced the fault was something between 2024.3.0 and 2024.4.4 inclusive, remembering that the installation on the Pi 5 has the problem with 2024.4.4.

**Comment by Farmer-Eds-Shed** [comment]
> @Farmer-Eds-Shed
> 
> > Maybe this is useful? Schedule triggered at 4:30 but next trigger time is showing as 4 min ago
> 
> Are you sure you are running the latest version? I thought this error was adressed a while ago, see: #343

@nielsfaber I was sure I was, as I updated through hacs last week. However I'm after reinstalling the component and card and it looks to be working as expected now. I'll report back if I still have an issue later. Thanks.

**Comment by AppleFlapp** [comment]
@Farmer-Eds-Shed @nielsfaber 
I did a full removal and reinstall of the component and card last week without success.
Maybe only one time that it worked as expected but that could also be the first time when it always succeeds
similar like when you toggle the schedules.

**Comment by Farmer-Eds-Shed** [comment]
> @Farmer-Eds-Shed @nielsfaber I did a full removal and reinstall of the component and card last week without success. Maybe only one time that it worked as expected but that could also be the first time when it always succeeds similar like when you toggle the schedules.

Maybe @AppleFlapp, but they ran this morning and are showing next execution as tomorrow instead of in the past. But time will tell.

**Comment by nielsfaber** [comment]
In an attempt to reproduce the issue, I created a schedule which changes an input_number entity 3 times per day (similar to the original problem description by @Marvin3241 )
<img src="https://github.com/nielsfaber/scheduler-component/assets/16861605/012bdf6e-fc92-4897-ad24-cf7b03516ff6" width="50%" height="50%">

I will check the history of the entity in a couple of days to see if any actions are missed.
If anyone has a better idea, please let me know.

**Comment by deveon95** [comment]
It's possible to downgrade Home Assistant Core using `ha core update --version x.y.z` so I've tried this to narrow down which version of the core stopped the scheduler from working properly.

2024.4.0 - affected; schedules only run once

2024.3.3 - not affected; Scheduler works normally

Downgrading to 2024.3.3 can be used as a temporary fix until someone figures out exactly what change in Home Assistant Core is causing the problem.

**Comment by nielsfaber** [comment]
My testing schedule as described [here](https://github.com/nielsfaber/scheduler-component/issues/352#issuecomment-2090957994) 


https://github.com/nielsfaber/scheduler-component/issues/352#issuecomment-2090957994

**Comment by sddgit** [comment]
What HA version are you running @nielsfaber ?

**Comment by sddgit** [comment]
Anyone have any further thoughts on this? I’m still hesitant to update HA in case my schedules break.

**Comment by deveon95** [comment]
It looks like @pdcastro is on to a winner and the fix was already done in one of the later issues of scheduler-component. I upgraded to 2024.4.0 specifically because I knew that version didn't work, then upgraded scheduler-component to the latest and now it's working fine. The developer couldn't reproduce the fault because they had already fixed it and were on the latest version.

So what's the lesson... just because everything is up to date under 'Settings' does not mean that everything is up to date under HACS so go there and check.

It's also a good reminder of why it's important to post version numbers of every relevant part of the system. Of course that works better when others then scrutinize those versions and point out when one isn't up to date.

**Comment by sddgit** [comment]
Thanks for the thoughts. I reckon I’ll update HA now!

**Comment by RogMoe** [comment]
I'm having the same issue.

Scheduler 3.3.3
Core 2024.6.0
Supervisor 2024.06.0
Operating System 12.3
Frontend 20240605.0

If I open the schedule, save and close, it sems to wake up en perform the forgotten action (no editing done).
I use the scheduler to set different ventilation modes.

![scheduler](https://github.com/nielsfaber/scheduler-component/assets/74535064/27178a34-b1ec-4db3-bacb-da560855ed15)
