### ISSUE TITLE
Deprecation warning that 'scheduler' calls `async_track_state_change` instead of `async_track_state_change_event`

### ISSUE THREAD

**Issue by user-08-151** [nielsfaber/scheduler-component#354]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
No warnings when using sheduler-component.

### Actual behavior
I'm getting following warning:
```
2024-05-02 12:27:55.977 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'scheduler' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/scheduler/__init__.py, line 428: self._workday_tracker = async_track_state_change(, please create a bug report at https://github.com/nielsfaber/scheduler-component/issues
```

### Steps to Reproduce
Add a task that run on workdays.

**Comment by h3nrytan** [comment]
Spotted this too:-

`Detected that custom integration 'scheduler' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/scheduler/actions.py, line 401: async_track_state_change(, please create a bug report at https://github.com/nielsfaber/scheduler-component/issues`

**Comment by Danifly80** [comment]
same for me:

`2024-05-14 09:36:13.242 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'scheduler' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/scheduler/__init__.py, line 428: self._workday_tracker = async_track_state_change(, please create a bug report at https://github.com/nielsfaber/scheduler-component/issues`

**Comment by JCummings49** [comment]
I’m getting a similar warning like 
this too.

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:190
First occurred: May 13, 2024 at 10:55:00 PM (1 occurrences)
Last logged: May 13, 2024 at 10:55:00 PM

Detected that custom integration 'scheduler' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/scheduler/actions.py, line 401: async_track_state_change(, please create a bug report at https://github.com/nielsfaber/scheduler-component/issues

**Comment by ferreto1978** [comment]
Same here:

`Detected that custom integration 'scheduler' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/scheduler/actions.py, line 401: async_track_state_change(, please create a bug report at https://github.com/nielsfaber/scheduler-component/issues
`

Not sure if this is helpfull, but the full message is:
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:190
First occurred: 07:55:28 (3 occurrences)
Last logged: 07:55:37

Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'scheduler' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/scheduler/actions.py, line 401: async_track_state_change(, please create a bug report at https://github.com/nielsfaber/scheduler-component/issues
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
```

**Comment by yepp31** [comment]
hi,
the same bug for me...😭😭

2024-06-10 21:53:06.814 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'scheduler' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/scheduler/actions.py, line 401: async_track_state_change(, please create a bug report at https://github.com/nielsfaber/scheduler-component/issues
