### ISSUE TITLE
Defective schedule entity can not be removed

### ISSUE THREAD

**Issue by m4v3r1ck1** [nielsfaber/scheduler-component#384]
<img width="311" alt="Screenshot 2024-10-26 at 11 20 00" src="https://github.com/user-attachments/assets/b38a4888-47d5-4a58-af98-df70d30e6c08">
<img width="579" alt="Screenshot 2024-10-26 at 11 20 25" src="https://github.com/user-attachments/assets/fc3adee9-4c5f-497b-8f45-381b269a978a">
<img width="316" alt="Screenshot 2024-10-26 at 11 20 34" src="https://github.com/user-attachments/assets/6c4dd3bc-daa7-4cb1-9ccb-8a2d772b46a0">

**Comment by hacscred** [comment]
This is a Home Assistant bug, I think. It's not specific to this integration. 

https://github.com/home-assistant/core/issues/11533 wanted an API to do this, which was shot down for a user hostile reason. The author of the RFC implemented an integration to allow deleting any entity, which if you install it, will also solve your problem.

**Comment by nielsfaber** [comment]
The scheduler integration offers a service `scheduler.remove` for manually removing schedules that cannot be displayed by scheduler card. 

Note that a schedule only becomes defective in case of user error where no timepoints can be calculated, e.g. configuring it to only repeat on Wednesdays and at the same time to only occur on 26/10/2024 which is an impossible combination. Can also be avoided by yourself.

**Comment by hacscred** [comment]
> The scheduler integration offers a service `scheduler.remove` for manually removing schedules that cannot be displayed by scheduler card.
> 
> Note that a schedule only becomes defective in case of user error where no timepoints can be calculated, e.g. configuring it to only repeat on Wednesdays and at the same time to only occur on 26/10/2024 which is an impossible combination. Can also be avoided by yourself.

Depending on who you want to use this, I can tell from experience that non-developers with a graduate technical degree can't follow such instructions out of laziness or stupidity. 

I don't know the reason for the concept of defective schedules to exist, but just displaying a message once every week with a link to some explanation seems better than bringing people to despair (opening such an issue is basically that). A schedule which would never run is an input validation issue and should just be tackled at the time of input. I think making it impossible to create defective schedules should be how it should work. 

I was able to figure it (using the remove call) out in minutes when I had the issue. Getting it to work programmatically with unknown entities was much more involved, but was needed during development. 

I make heavy use of the remove API call, because I compute almost all schedules from external data. I literally don't even know when things go on and off. (I suppose I should add some cyber resilience to it, because switching lights 600 times per day is not exactly good for the electronics. It would be a fairly good attack vector for an adversary to destabilize the grid at scale. So, I would suggest you add both default jitter (I think you already do that) and a maximum number of actions per schedule and perhaps even in total, unless someone specifically configures some option to not limit it or set another limit. Crossing the limit could also act as a kind of tripwire. Perhaps something like it could be generalized for Home Assistant in general as well. )

(I think Home Assistant developers don't want people to do high quality stable deployments of Home Assistant in order to make their products more enticing. Kind of annoying. I hope a true community fork will happen someday. )

**Comment by m4v3r1ck1** [comment]
> `scheduler.remove`

How can I trigger this service? I the integration I can not find directly any service which I could trigger.
<img width="541" alt="Screenshot 2024-10-26 at 13 19 32" src="https://github.com/user-attachments/assets/6e84817f-ea1b-4c52-bd95-069a42624a35">
<img width="666" alt="Screenshot 2024-10-26 at 13 19 52" src="https://github.com/user-attachments/assets/c9bd1518-e9f1-475b-be99-b4147b308940">

**Comment by hacscred** [comment]
Under Developer tools, actions. 

(Such simple questions can also be answered by LLMs. )
