### ISSUE TITLE
Zigbee Device (Osram plug) is turned ON but never turned OFF in schedule

### ISSUE THREAD

**Issue by FrankSchoene** [nielsfaber/scheduler-component#387]
Device: Osram Smart+ Plug 
Connection via Z2M

### Checklist
- [ x] I checked for similar existing issues (both open and closed) before posting.
- [ v0.0.0] I am running the latest version.

### Expected behavior
[What you expected to happen]
Zigbee (Osram) Switches are turned ON and OFF according to schedule

### Actual behavior
[What actually happened]
Switches are turned on in time but never turned off

### Steps to Reproduce
[Explain how to see the behaviour]
The lights are still on :-)

**Comment by hacscred** [comment]
This has nothing to do with this custom component. 

Either your coordinator is broken or the switches are. 

Perhaps if you were to report actual details about your setup on the Home Assistant forum, that someone could help you. Buying a new coordinator and new switches of a different brand will probably fix all your issues.

Can you explain why you think a component that is working for probably tens of thousands of switches should contain a bug just because it's not working for you? 

A bug is a demonstration between observed behavior and correct behavior. While your system has a bug, this doesn't mean at all that the problem is inside this custom component. 

Please think before opening an issue.

**Comment by hacscred** [comment]
The manual says that you need to specify behavior for every minute of the day. So, do you have a block with turn on and a block with turn off? 

If not, that's your problem.
