### ISSUE TITLE
Scheduler is changing the climate offset attribute instead of the target temperature (I think!)

### ISSUE THREAD

**Issue by maxm77-RC** [nielsfaber/scheduler-component#391]
Hello, I am using both the scheduler component and the scheduler card with a Tado heating system.

I have it setup as per the screenshots below 
It is supposed to set the heating to 21C twice a day and the rest of the time turn it off.

<img width="560" alt="Scheduler card 1" src="https://github.com/user-attachments/assets/4bea3d6e-ea9d-433e-994d-684351055872">
<img width="539" alt="Scheduler card 2" src="https://github.com/user-attachments/assets/985ba8b0-b3c1-4e7a-9f93-b3cddc142e46">
<img width="549" alt="Scheduler card 3" src="https://github.com/user-attachments/assets/75c599e2-dda8-4fd8-8ca3-b5b0403d3a5e">

It took me a while to realise there was a problem, but I noticed that the internal temperature was registering at circa 10C (I have another independent sensor which registered about 19C when the heating was off). 
When checking the Tado app, I saw that the "Temperature offset" was being set by something (not me!) hence the internal temperature being much lower than it actually is.
![Tado offset](https://github.com/user-attachments/assets/9de60a63-009a-46a2-a7bb-1d8c519a1b6f)

I then looked at the Heating logbook and saw that the "offset" was being altered rather than the target temperature. 
<img width="598" alt="Logbook for Heating" src="https://github.com/user-attachments/assets/5a368bcf-a5f0-4702-b088-ff5207fb11b6">

I can't work out why. 
Any tips would be very welcome. 
Thanks

### Checklist
- [I can't see anything similar ] I checked for similar existing issues (both open and closed) before posting.
- [Yes ] I am running the latest version.

### Expected behavior
[Scheduler update the target temperature]

### Actual behavior
[Temperature Offset attribute being updated instead]

I have not managed to work out how to find the logs for this.

**Comment by nielsfaber** [comment]
Scheduler will call the service `climate.set_temperature` to change the temperature setpoint (unless you customized the actions in the scheduler-card via yaml).
If `climate.set_temperature` causes the offset to be changed instead of the setpoint, that is an issue of your integration. 
Note that I am also using scheduler for controlling my tado TRV valves, I don't experience any issues.

If you want to investigate this further, you can enable debug logging for scheduler by adding this to the configuration.yaml
```yaml
logger:
  default: warning
  logs:
    custom_components.scheduler: debug
```

It will cause extra information to be displayed in the HA logs when a schedule is triggered, including the services that are called.
Please share your findings.
