### ISSUE TITLE
Possibility to rerun/retry selected schedule

### ISSUE THREAD

**Issue by diabl0** [nielsfaber/scheduler-component#76]
As HA services are gone i need a way to "rerun" selected schedule.

I love how easily i can setup different schedules using scheduler-card right from HA. But i also need to integrate window detection. I'm using node-red for that - if window is opened set temperature to 5°C. And then i need to reset/back to  scheduled temperature when window is closed. Same is for leave/arrive, vacation mode etc. automations... 
 
Currently only way i found to force rerun schedule is to turn off and then turn on coresponding switch (eg. switch.schedule_9d8b7d_2), but this is hacky and adds another complexity if schedule is off for some reason (eg. heating during summer).

**Comment by nielsfaber** [comment]
You mean the scheduler.test function?
It was really only meant for testing/debugging purposes.
I figured it was harmless to remove since there is no 'test' button in the card so the function remains unused. 
If people see it useful, i will bring it back.

For your specific case, disabling/enabling the schedule doesn't seem like a bad idea to me actually.
It's really recommended to disable a schedule once you 'overrule' it with other automations.

Anyway, if the retriggering the actions by service call is easiest for you, i can make a service for this.
I would say such service should automatically execute the actions of the current timeslot, and maybe it would be better to have optional argument for a given timepoint for which you want to trigger the action.
This seems more intuitive to me than using timeslot number/index.
What do you think?

**Comment by diabl0** [comment]
Yes, it would be great help to combine scheduler with other automations (and i hope that not only for me).

**Comment by nielsfaber** [comment]
I added a service `scheduler.run_action` for this.
You need to call it with the entity ID of the schedule for which you want to run the action (same as `scheduler.test`.

For schedules with multiple timeslots, you can add an argument `time` (e.g. `08:00`), to have the actions for a specific time triggered.
This defaults to the current time.

I thought this would be easier to work with than based on timeslot numbers.

**Comment by nielsfaber** [comment]
@diabl0 I will close this issue, assuming the added service is helpful for you.
If there are any troubles, let me know.
